apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: uvote-dev

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: election-service
  namespace: uvote-dev

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: voting-service
  namespace: uvote-dev

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: results-service
  namespace: uvote-dev

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-service
  namespace: uvote-dev

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-service
  namespace: uvote-dev
