apiVersion: v1
kind: Service
metadata:
  name: frontend-prod-lb
  namespace: uvote-prod
  labels:
    app: frontend-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: frontend-service
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
