apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uvote-prod

resources:
  - ../../base
  - secrets.yaml
  - frontend-lb.yaml

patches:
  # Scale all backend services to 2 replicas for prod
  - path: replicas-patch.yaml
    target:
      kind: Deployment
  # Enable Quick Setup Guide feature flag on election-service only
  - path: feature-flag-patch.yaml
    target:
      kind: Deployment
      name: election-service
  # Use permissive peer auth so the external LoadBalancer can reach frontend
  - path: peer-auth-patch.yaml
    target:
      kind: PeerAuthentication

# Image tags — updated by CI update-manifests job on main push
images:
  - name: auth-service
    newName: 484010150615.dkr.ecr.eu-west-1.amazonaws.com/uvote/auth-service
    newTag: "5aea318"
  - name: admin-service
    newName: 484010150615.dkr.ecr.eu-west-1.amazonaws.com/uvote/admin-service
    newTag: "5aea318"
  - name: voting-service
    newName: 484010150615.dkr.ecr.eu-west-1.amazonaws.com/uvote/voting-service
    newTag: "5aea318"
  - name: results-service
    newName: 484010150615.dkr.ecr.eu-west-1.amazonaws.com/uvote/results-service
    newTag: "5aea318"
  - name: election-service
    newName: 484010150615.dkr.ecr.eu-west-1.amazonaws.com/uvote/election-service
    newTag: "5aea318"
  - name: frontend-service
    newName: 484010150615.dkr.ecr.eu-west-1.amazonaws.com/uvote/frontend-service
    newTag: "5aea318"
