apiVersion: v1
kind: Secret
metadata:
  name: db-connection
type: Opaque
stringData:
  host: "uvote-dev-postgres.cl6omcueky8x.eu-west-1.rds.amazonaws.com"
  port: "5432"
  database: "voting_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  username: "uvote_admin"
  password: "uVote2026"
  postgres-password: "uVote2026"
  database: "voting_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  secret: "uVoteJWT2026SecureSigningKeyForHSA256AuthTokens!!"
---
apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
type: Opaque
stringData:
  secret: "uVoteFlask2026SessionSecretKeyForCSRFAndCookies!!"
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-credentials
type: Opaque
stringData:
  SMTP_HOST: "mailhog"
  SMTP_PORT: "1025"
  SMTP_USE_TLS: "false"
  SMTP_USE_SSL: "false"
  SMTP_FROM: "noreply@uvote.local"
  SMTP_USER: ""
  SMTP_PASS: ""
  FRONTEND_URL: "http://localhost"
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-db-credentials
type: Opaque
stringData:
  username: "uvote_admin"
  password: "uVote2026"
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-db-credentials
type: Opaque
stringData:
  username: "uvote_admin"
  password: "uVote2026"
---
apiVersion: v1
kind: Secret
metadata:
  name: voting-db-credentials
type: Opaque
stringData:
  username: "uvote_admin"
  password: "uVote2026"
---
apiVersion: v1
kind: Secret
metadata:
  name: election-db-credentials
type: Opaque
stringData:
  username: "uvote_admin"
  password: "uVote2026"
---
apiVersion: v1
kind: Secret
metadata:
  name: results-db-credentials
type: Opaque
stringData:
  username: "uvote_admin"
  password: "uVote2026"
