apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: istio-system
data:
  config.yaml: |
    auth:
      strategy: anonymous
    deployment:
      accessible_namespaces:
      - istio-system
      - uvote-dev
    external_services:
      prometheus:
        url: "http://prometheus.istio-system.svc.cluster.local:9090"
      tracing:
        enabled: true
        in_cluster_url: "http://tracing.istio-system.svc.cluster.local:80"
        use_grpc: false
      grafana:
        enabled: true
        in_cluster_url: "http://grafana.istio-system.svc.cluster.local:3000"
