global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: auth-service
    static_configs:
      - targets: ['auth-service:5001']
    metrics_path: /metrics

  - job_name: admin-service
    static_configs:
      - targets: ['admin-service:5002']
    metrics_path: /metrics

  - job_name: voting-service
    static_configs:
      - targets: ['voting-service:5003']
    metrics_path: /metrics

  - job_name: results-service
    static_configs:
      - targets: ['results-service:5004']
    metrics_path: /metrics

  - job_name: election-service
    static_configs:
      - targets: ['election-service:5005']
    metrics_path: /metrics

  - job_name: frontend-service
    static_configs:
      - targets: ['frontend-service:5000']
    metrics_path: /metrics
