apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend-service
spec:
  template:
    spec:
      containers:
        - name: frontend-service
          env:
            - name: ELECTION_DASHBOARD_URL
              value: "/dashboard"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: secret
