apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uvote-dev

resources:
  - ../../base
  - secrets.yaml

# Image tags — updated by CI update-manifests job on mvp_tests push
images:
  - name: auth-service
    newName: 484010150615.dkr.ecr.eu-west-1.amazonaws.com/uvote/auth-service
    newTag: "e2b0050"
  - name: admin-service
    newName: 484010150615.dkr.ecr.eu-west-1.amazonaws.com/uvote/admin-service
    newTag: "e2b0050"
  - name: voting-service
    newName: 484010150615.dkr.ecr.eu-west-1.amazonaws.com/uvote/voting-service
    newTag: "e2b0050"
  - name: results-service
    newName: 484010150615.dkr.ecr.eu-west-1.amazonaws.com/uvote/results-service
    newTag: "e2b0050"
  - name: election-service
    newName: 484010150615.dkr.ecr.eu-west-1.amazonaws.com/uvote/election-service
    newTag: "e2b0050"
  - name: frontend-service
    newName: 484010150615.dkr.ecr.eu-west-1.amazonaws.com/uvote/frontend-service
    newTag: "e2b0050"
