apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: election-service

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: voting-service

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: results-service

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-service

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-service
