apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: auth-service
  namespace: uvote-dev
spec:
  host: auth-service
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 100
        http2MaxRequests: 1000
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 30s
      baseEjectionTime: 30s
    tls:
      mode: ISTIO_MUTUAL

---

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: election-service
  namespace: uvote-dev
spec:
  host: election-service
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 100
        http2MaxRequests: 1000
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 30s
      baseEjectionTime: 30s
    tls:
      mode: ISTIO_MUTUAL

---

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: voting-service
  namespace: uvote-dev
spec:
  host: voting-service
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 100
        http2MaxRequests: 1000
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 30s
      baseEjectionTime: 30s
    tls:
      mode: ISTIO_MUTUAL

---

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: results-service
  namespace: uvote-dev
spec:
  host: results-service
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 100
        http2MaxRequests: 1000
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 30s
      baseEjectionTime: 30s
    tls:
      mode: ISTIO_MUTUAL

---

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: admin-service
  namespace: uvote-dev
spec:
  host: admin-service
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 100
        http2MaxRequests: 1000
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 30s
      baseEjectionTime: 30s
    tls:
      mode: ISTIO_MUTUAL

---

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: frontend-service
  namespace: uvote-dev
spec:
  host: frontend-service
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 100
        http2MaxRequests: 1000
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 30s
      baseEjectionTime: 30s
    tls:
      mode: ISTIO_MUTUAL
